<a href="https://colab.research.google.com/github/MahjoubiAzer1/lab-agile-planning/blob/main/Memoire_Code.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#this code is used  for  Labilisation Phase


import pandas as pd

# Read the CSV file
data = pd.read_csv('/content/drive/MyDrive/ReadyLDA.csv')

# Check if "category" column exists and remove it if present
if 'category' in data.columns:
    data = data.drop(columns=['category'])

# Define category mappings
category_mappings = {
    '0': 'sport',
    '1': 'politics',
    '2': 'health',
    '3': 'entrepreneurship',
    '4': 'others'
}
# Iterate over the phrases
for index, row in data.iterrows():
    phrase = row['phrase']
    # Prompt for category input
    valid_input = False
    while not valid_input:
        category = input(f"Enter category for phrase '{phrase}' (0:sport, 1:politics, 2:health, 3:entrepreneurship, 4:others, TITI to stop): ")
        if category.lower() == 'titi':
            valid_input = True
            break
        elif category in category_mappings:
            valid_input = True
        else:
            print("Invalid category! Please enter a valid category or 'TITI' to stop.")

    # Check if the user wants to stop
    if category.lower() == 'titi':
        break

    # Assign the category
    data.at[index, 'category'] = category_mappings[category]

# Write back to the CSV file
data.to_csv('updated_file.csv', index=False)


KeyboardInterrupt: ignored

In [8]:
!git config --global user.name "MahjoubiAzer1"
!git config --global user.email "mahjoubiazer@gmail.com"


In [1]:
import subprocess

# Define the Git commands
commands = [
    "git remote add origin https://github.com/MahjoubiAzer1/Memoire.git",
    "git branch -M main",
    "git push -u origin main"
]

# Execute the Git commands one by one
for command in commands:
    process = subprocess.Popen(command.split(), stdout=subprocess.PIPE, stderr=subprocess.PIPE)
    output, error = process.communicate()

    if process.returncode == 0:
        print(f"Command '{command}' executed successfully")
    else:
        print(f"Error executing command '{command}': {error.decode('utf-8')}")



Error executing command 'git remote add origin https://github.com/MahjoubiAzer1/Memoire.git': fatal: not a git repository (or any of the parent directories): .git

Error executing command 'git branch -M main': fatal: not a git repository (or any of the parent directories): .git

Error executing command 'git push -u origin main': fatal: not a git repository (or any of the parent directories): .git



In [ ]:
#LDA Model Working        With Evaluation Metrics    accuracy ()  precision    recall  f1-score   support for each topic )

import pandas as pd
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.decomposition import LatentDirichletAllocation
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score, f1_score
import numpy as np

# Load the CSV file
data = pd.read_csv('/content/drive/MyDrive/updated_file.csv')


# Drop rows with missing values
data = data.dropna(subset=['phrase', 'category'])

# Split the data into training and testing sets
train_data, test_data = train_test_split(data, test_size=0.2, random_state=42)

# Preprocess the text data
vectorizer = CountVectorizer()
X_train = vectorizer.fit_transform(train_data['phrase'])
X_test = vectorizer.transform(test_data['phrase'])

# Create a dictionary for category labels
category_dict = {
    'sport': 0,
    'politics': 1,
    'health': 2,
    'entrepreneurship': 3,
    'others': 4
}

# Map phrases to category labels
y_train = train_data['category'].map(category_dict)
y_test = test_data['category'].map(category_dict)

# Check for any remaining NaN values in y_test
if y_test.isnull().values.any():
    # Fill NaN values with a default label or a specific value of your choice
    y_test = y_test.fillna('default')

# Train the LDA model
lda_model = LatentDirichletAllocation(n_components=5, random_state=42)
lda_model.fit(X_train)

# Predict the categories for the test set
y_pred = lda_model.transform(X_test).argmax(axis=1)

# Convert the predicted labels back to category names
predicted_categories = pd.Series(y_pred).map({v: k for k, v in category_dict.items()})

# Calculate evaluation metrics
confusion_mat = confusion_matrix(y_test, y_pred)
accuracy = accuracy_score(y_test, y_pred)
f1 = f1_score(y_test, y_pred, average='weighted')

# Print the evaluation metrics
print("Confusion Matrix:")
print(confusion_mat)
print("\nAccuracy:", accuracy)
print("\nF1-score:", f1)
print("\nClassification Report:")
print(classification_report(y_test, y_pred, target_names=category_dict.keys()))


Confusion Matrix:
[[0 0 0 0 0]
 [1 0 0 0 0]
 [1 0 0 0 0]
 [1 3 0 1 0]
 [1 1 1 0 1]]

Accuracy: 0.18181818181818182

F1-score: 0.296969696969697

Classification Report:
                  precision    recall  f1-score   support

           sport       0.00      0.00      0.00         0
        politics       0.00      0.00      0.00         1
          health       0.00      0.00      0.00         1
entrepreneurship       1.00      0.20      0.33         5
          others       1.00      0.25      0.40         4

        accuracy                           0.18        11
       macro avg       0.40      0.09      0.15        11
    weighted avg       0.82      0.18      0.30        11



/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [ ]:
#HDPModel Working        With Evaluation Metrics    accuracy ()  precision    recall  f1-score   support for each topic )


import pandas as pd
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.decomposition import LatentDirichletAllocation
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score, f1_score
from sklearn.decomposition import NMF
from sklearn.decomposition import TruncatedSVD
from sklearn.decomposition import LatentDirichletAllocation as LDA
from sklearn.decomposition import MiniBatchDictionaryLearning
from sklearn.decomposition import SparsePCA
from sklearn.decomposition import MiniBatchSparsePCA
from sklearn.decomposition import FactorAnalysis
from sklearn.decomposition import FastICA
from sklearn.decomposition import PCA
from sklearn.decomposition import MiniBatchSparsePCA
from sklearn.decomposition import LatentDirichletAllocation as LDA
from sklearn.decomposition import LatentDirichletAllocation
from sklearn.decomposition import LatentDirichletAllocation
from sklearn.decomposition import LatentDirichletAllocation

# Load the CSV file
data = pd.read_csv('/content/drive/MyDrive/updated_file.csv')

# Drop rows with missing values
data = data.dropna(subset=['phrase', 'category'])

# Split the data into training and testing sets
train_data, test_data = train_test_split(data, test_size=0.2, random_state=42)

# Preprocess the text data
vectorizer = CountVectorizer()
X_train = vectorizer.fit_transform(train_data['phrase'])
X_test = vectorizer.transform(test_data['phrase'])

# Create a dictionary for category labels
category_dict = {
    'sport': 0,
    'politics': 1,
    'health': 2,
    'entrepreneurship': 3,
    'others': 4
}

# Map phrases to category labels
y_train = train_data['category'].map(category_dict)
y_test = test_data['category'].map(category_dict)

# Check for any remaining NaN values in y_test
if y_test.isnull().values.any():
    # Fill NaN values with a default label or a specific value of your choice
    y_test = y_test.fillna('default')

# Train the HDP model
hdp_model = LatentDirichletAllocation(n_components=5, random_state=42)
hdp_model.fit(X_train)

# Predict the categories for the test set
y_pred = hdp_model.transform(X_test).argmax(axis=1)

# Convert the predicted labels back to category names
predicted_categories = pd.Series(y_pred).map({v: k for k, v in category_dict.items()})

# Calculate evaluation metrics
confusion_mat = confusion_matrix(y_test, y_pred)
accuracy = accuracy_score(y_test, y_pred)
f1 = f1_score(y_test, y_pred, average='weighted')

# Print the evaluation metrics
print("Confusion Matrix:")
print(confusion_mat)
print("\nAccuracy:", accuracy)
print("\nF1-score:", f1)
print("\nClassification Report:")
print(classification_report(y_test, y_pred, target_names=category_dict.keys()))



Confusion Matrix:
[[0 0 0 0 0]
 [1 0 0 0 0]
 [1 0 0 0 0]
 [1 3 0 1 0]
 [1 1 1 0 1]]

Accuracy: 0.18181818181818182

F1-score: 0.296969696969697

Classification Report:
                  precision    recall  f1-score   support

           sport       0.00      0.00      0.00         0
        politics       0.00      0.00      0.00         1
          health       0.00      0.00      0.00         1
entrepreneurship       1.00      0.20      0.33         5
          others       1.00      0.25      0.40         4

        accuracy                           0.18        11
       macro avg       0.40      0.09      0.15        11
    weighted avg       0.82      0.18      0.30        11



/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [ ]:
#Translation using google API 10000 by 10000  ( after translation  use fusion algorithm to make on file of the translatoin )

!pip install googletrans==4.0.0-rc1

import pandas as pd
from google.colab import drive
from googletrans import Translator
import os
from tqdm import tqdm  # Import the tqdm library

# Mount Google Drive to access the dataset
drive.mount('/content/drive')

# Check if the file exists
file_path = '/content/drive/MyDrive/d/Samawel.csv'
if not os.path.isfile(file_path):
    print("File not found:", file_path)
else:
    # Load the dataset
    df = pd.read_csv(file_path)

    # Create a translator object
    translator = Translator(service_urls=['translate.google.com'])

    # Define a function to translate a text from Tunisian Arabic to English
    def translate(text):
        try:
            translation = translator.translate(text, src='ar', dest='en').text
        except:
            translation = ''
        return translation

    # Extract the 'text_clean' column as a list of strings
    text_list = df['text_clean'].tolist()

    batch_size = 1000
    start_index = 0

    while start_index < len(text_list):
        end_index = start_index + batch_size
        batch_text = text_list[start_index:end_index]

        # Translate the batch of text
        translated_texts = []
        for text in tqdm(batch_text, desc="Translating"):
            translated_texts.append(translate(text))

        # Add the translated text to the DataFrame
        df_batch = pd.DataFrame({'text_clean': batch_text, 'text_clean_en': translated_texts})
        output_file_path = f'/content/drive/MyDrive/Documents/Data_batch_{start_index + 1}.csv'
        df_batch.to_csv(output_file_path, index=False)
        print(f"Batch {start_index // batch_size + 1} (lines {start_index + 1}-{end_index}) saved to:", output_file_path)

        start_index = end_index

print("All translations completed.")

In [ ]:
# translation is made 1000 rows per 1000 rows saved in myltiple file   this code willl  merge the  file in the correct order , ( version is not for google collab  run it  on your visual studio code for exmaple  ( order is  garanted by the code  ))


import pandas as pd
import os

# Path to the directory where the CSV files are located
directory_path = './'  # Change this to the path of your directory

# Generate list of file names
file_names = [f"DATA_Batch_{i}.csv" for i in range(1001, 200001, 1000)]

# Initialize an empty DataFrame
final_df = pd.DataFrame()

# Loop through each file and append its content to final_df
for file_name in file_names:
    file_path = os.path.join(directory_path, file_name)
    if os.path.exists(file_path):
        df = pd.read_csv(file_path)
        final_df = final_df.append(df)

# Write the final DataFrame to an output CSV file
output_file_path = os.path.join(directory_path, 'Merged_DATA.csv')
final_df.to_csv(output_file_path, index=False)


In [ ]:
#translation with openai api (paid)   ( Don't Forget to create you own api key and put it  in  ("SK-XXXXXXXXXX")  )  version is  for google collab  ( you can get 18 $ of transaction for free when you enter  payement information )



 import openai

# Define your OpenAI API key
api_key = "YOUR_API_KEY"

# Initialize the OpenAI API client
openai.api_key = api_key

# Define a function for translation
def translate_to_english(text):
    # Make a request to the API for translation
    response = openai.Completion.create(
        engine="davinci-codex",
        prompt=f"Translate the following Tunisian text to English:\n\n{text}",
        max_tokens=100,
        n=1,
        stop=["\n"]
    )

    # Extract the translated text from the response
    translation = response.choices[0].text.strip()

    return translation

# Example data
data = [
    ['tyuy', ''],
    ['tres pratique facile', ''],
    ['super bien', '']
]

# Translate each item in the data
translated_data = []

for item in data:
    tunisian_text = item[0]
    english_translation = translate_to_english(tunisian_text)
    translated_data.append([tunisian_text, english_translation])

# Print the translated data
for item in translated_data:
    print(item)



In [ ]:
 #Statistical translation technic
!pip install nltk
import nltk
from nltk.translate import IBMModel1
from nltk.tokenize import word_tokenize

# Download the necessary resources
nltk.download('punkt')
nltk.download('comtrans')

# Prepare parallel text data
bitext = nltk.corpus.comtrans.aligned_sents()

# Train IBM Model
ibm1 = IBMModel1(bitext, 5)

# Define a function for translation
def translate_to_english(text):
    # Tokenize the input text
    tokens = word_tokenize(text)

    # Translate using IBM Model 1
    translation = ibm1.align(tokens)

    # Extract English words from the translation
    english_translation = [pair[1] for pair in translation]

    return ' '.join(english_translation)

# Example data
data = [
    ['tyuy', ''],
    ['tres pratique facile', ''],
    ['super bien', '']
]

# Translate each item in the data
translated_data = []

for item in data:
    tunisian_text = item[0]
    english_translation = translate_to_english(tunisian_text)
    translated_data.append([tunisian_text, english_translation])

# Print the translated data
for item in translated_data:
    print(item)


[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.
[nltk_data] Downloading package comtrans to /root/nltk_data...


KeyboardInterrupt: ignored

In [ ]:
#this script is used to delete the first column ( which is  the original data and let the translated version to give toi the  process greed search/random search and give to the LDA/HDP models  )
from pydrive.auth import GoogleAuth
from pydrive.drive import GoogleDrive
import csv

# Authenticate and create GoogleDrive instance
gauth = GoogleAuth()
gauth.LocalWebserverAuth()
drive = GoogleDrive(gauth)


 # Mount Google Drive to access the dataset
drive.mount('/content/drive')

# Check if the file exists
file_path = '/content/drive/MyDrive/d/Samawel.csv'


# Read the CSV file and remove the first column
with open('input.csv', 'r') as infile, open('output.csv', 'w', newline='') as outfile:
    reader = csv.reader(infile)
    writer = csv.writer(outfile)
    for row in reader:
        writer.writerow(row[1:])  # Write all columns except the first one

# Upload the modified file back to Google Drive
modified_file = drive.CreateFile({'title': 'output.csv'})
modified_file.Upload()

# Clean up local files
os.remove('input.csv')
os.remove('output.csv')

print("First column deleted and file updated on Google Drive.")


In [ ]:
#EANDOM SEARCH LDA FINDING OPTIMAL PARAMETERS
 # Importing necessary libraries
import pandas as pd
from sklearn.decomposition import LatentDirichletAllocation
from sklearn.model_selection import RandomizedSearchCV
from sklearn.feature_extraction.text import CountVectorizer

# Mount Google Drive
from google.colab import drive
drive.mount('/content/drive')

# Load the dataset from Google Drive
file_path = "/content/drive/MyDrive/DATA BATCH 3/Data_batch_4002.csv"  # Provide the correct path
data = pd.read_csv(file_path)

# Use the second column only
texts = data['text_clean_en'].dropna().tolist()

# Convert text data to a matrix of token counts
vectorizer = CountVectorizer(stop_words='english', max_df=0.95, min_df=2)
X = vectorizer.fit_transform(texts)

# Define LDA model and parameters grid for random search
lda = LatentDirichletAllocation(learning_method='online')

params = {
    'n_components': [5, 10, 15, 20],  # or any other values you are interested in
    'learning_decay': [0.5, 0.7, 0.9],  # common values for lda
    'doc_topic_prior': [None] + list(10.0**(-i) for i in range(5)),  # alpha parameter, including the default value (None)
    'topic_word_prior': [None] + list(10.0**(-i) for i in range(5))  # beta parameter, including the default value (None)
}

# Random Search for best LDA parameters
search = RandomizedSearchCV(lda, param_distributions=params, n_iter=30, n_jobs=-1)
search.fit(X)

print("Best Model's Params: ", search.best_params_)
print("Best Log Likelihood Score: ", search.best_score_)

# Fit the best LDA model
best_lda = search.best_estimator_
best_lda.fit(X)


Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


KeyboardInterrupt: ignored

In [ ]:
 #used for deleting lines ( put range if needed )


 from google.colab import drive
drive.mount('/content/drive')
import pandas as pd

# Path to your file on Google Drive
file_path = '/content/drive/MyDrive/DATA BATCH 3/Data_batch_4002.csv'

# Load the CSV into a DataFrame
df = pd.read_csv(file_path)

# Drop lines 2 to 981 (inclusive)
df = df.drop(index=range(1, 981))

# Save the modified DataFrame back to the CSV
df.to_csv(file_path, index=False)

In [ ]:
#PARAMETER TUNNING  GREED SEARCH LDA ( ALPHA AND BETA  )


# Importing necessary libraries
import pandas as pd
from sklearn.decomposition import LatentDirichletAllocation
from sklearn.model_selection import GridSearchCV
from sklearn.feature_extraction.text import CountVectorizer

# Mount Google Drive
from google.colab import drive
drive.mount('/content/drive')

# Load the dataset from Google Drive
file_path = '/content/drive/MyDrive/DATA BATCH 3/Data_batch_4002.csv'
data = pd.read_csv(file_path)

# Use the second column only
texts = data['text_clean_en'].dropna().tolist()

# Convert text data to a matrix of token counts
vectorizer = CountVectorizer(stop_words='english', max_df=0.95, min_df=2)
X = vectorizer.fit_transform(texts)

# Define LDA model and parameters grid for grid search
lda = LatentDirichletAllocation(learning_method='online')

params = {
    'n_components': [5, 10, 15, 20],  # or any other values you are interested in
    'learning_decay': [0.5, 0.7, 0.9],  # common values for lda
    'doc_topic_prior': [None] + list(10.0**(-i) for i in range(5)),  # alpha parameter, including the default value (None)
    'topic_word_prior': [None] + list(10.0**(-i) for i in range(5))  # beta parameter, including the default value (None)
}

# Grid Search for best LDA parameters
search = GridSearchCV(lda, param_grid=params, n_jobs=-1, verbose=1)
search.fit(X)

print("Best Model's Params: ", search.best_params_)
print("Best Log Likelihood Score: ", search.best_score_)

# Fit the best LDA model
best_lda = search.best_estimator_
best_lda.fit(X)




Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
Fitting 5 folds for each of 432 candidates, totalling 2160 fits
Best Model's Params:  {'doc_topic_prior': 1.0, 'learning_decay': 0.9, 'n_components': 5, 'topic_word_prior': 1.0}
Best Log Likelihood Score:  -25.463771963859877


LatentDirichletAllocation(doc_topic_prior=1.0, learning_decay=0.9,
                          learning_method='online', n_components=5,
                          topic_word_prior=1.0)

In [ ]:
#RANDOM SEARCH HDP MODEL
 import numpy as np
import gensim
from gensim.models import HdpModel
from gensim.corpora import Dictionary
from random import choice
import pandas as pd

# Load dataset from Google Drive
data_path = '/content/drive/MyDrive/DATA BATCH 3/Data_batch_4002.csv'
data = pd.read_csv(data_path)
texts = data['text_clean_en'].dropna().apply(lambda x: x.split()).tolist() # assuming space-separated words

dictionary = Dictionary(texts)
corpus = [dictionary.doc2bow(text) for text in texts]

# Hyperparameters to sample from
alpha_values = np.linspace(0.1, 2, 10)
gamma_values = np.linspace(0.1, 2, 10)

best_coherence = -np.inf
best_params = None

# Random Search
for _ in range(20):  # 20 iterations
    alpha = choice(alpha_values)
    gamma = choice(gamma_values)

    model = HdpModel(corpus, dictionary, alpha=alpha, gamma=gamma)
    coherence = gensim.models.CoherenceModel(model=model, texts=texts, dictionary=dictionary, coherence='c_v').get_coherence()

    if coherence > best_coherence:
        best_coherence = coherence
        best_params = (alpha, gamma)

print("Best Alpha, Gamma:", best_params)
print("Best Coherence:", best_coherence)


Best Alpha, Gamma: (0.9444444444444444, 1.1555555555555557)
Best Coherence: 0.6324767793434374


In [ ]:
#GRID SEARCH HDP MODEL

best_coherence = -np.inf
best_params = None

# Grid Search
for alpha in alpha_values:
    for gamma in gamma_values:
        model = HdpModel(corpus, dictionary, alpha=alpha, gamma=gamma)
        coherence = gensim.models.CoherenceModel(model=model, texts=texts, dictionary=dictionary, coherence='c_v').get_coherence()

        if coherence > best_coherence:
            best_coherence = coherence
            best_params = (alpha, gamma)

print("Best Alpha, Gamma:", best_params)
print("Best Coherence:", best_coherence)


Best Alpha, Gamma: (0.3111111111111111, 1.788888888888889)
Best Coherence: 0.63347303813736


In [ ]:
#mergin translated patch ( we did translation 1000  by 1000 in order to prevent system fails )


# Step 1: Mount Google Drive
from google.colab import drive
drive.mount('/content/drive')

# Step 2: List the Files and Sort
import os
folder_path = "/content/drive/MyDrive/Batch1-50"
files = [f for f in os.listdir(folder_path) if f.endswith('.csv')]
files.sort(key=lambda x: int(x.split('_')[2].split('.')[0]))  # Sorting in the desired order.

# Step 3: Merge the Files using Pandas
import pandas as pd
dfs = []  # List to store dataframes
for file in files:
    df = pd.read_csv(os.path.join(folder_path, file))
    dfs.append(df)
merged_df = pd.concat(dfs, ignore_index=True)

# Step 4: Save the Merged DataFrame
output_path = "/content/drive/MyDrive/Batch1-50"
merged_df.to_csv(output_path, index=False)


Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


IndexError: ignored